version: '3.8'

services:
  db-test:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=actaai_test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend-test:
    build: ./backend
    depends_on:
      db-test:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db-test:5432/actaai_test
      - SECRET_KEY=test_secret_key
      - OPENAI_API_KEY=sk-test
      - TESTING=True
    volumes:
      - ./backend:/app
    command: bash -c "pip install pytest pytest-asyncio httpx aiosqlite && pytest -xvs" 