#!/bin/bash

# Acta AI Services Startup Script
# This script checks for port conflicts and starts the services with available ports

set -e

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Function to print colorful messages
print_message() {
  echo -e "${GREEN}[Acta AI]${NC} $1"
}

print_warning() {
  echo -e "${YELLOW}[Warning]${NC} $1"
}

print_error() {
  echo -e "${RED}[Error]${NC} $1"
}

# Function to check if a port is in use
is_port_in_use() {
  if lsof -Pi :$1 -sTCP:LISTEN -t >/dev/null ; then
    return 0  # Port is in use
  else
    return 1  # Port is free
  fi
}

# Default ports
FRONTEND_PORT=3000
BACKEND_PORT=8000
DB_PORT=5432

# Check and find available ports
print_message "Checking for port availability..."

# Check frontend port
if is_port_in_use $FRONTEND_PORT; then
  print_warning "Port $FRONTEND_PORT is already in use. Finding an alternative port for frontend..."
  # Try to find an available port
  for port in $(seq 3001 3010); do
    if ! is_port_in_use $port; then
      print_message "Using port $port for frontend"
      FRONTEND_PORT=$port
      break
    fi
  done
  
  if [ $FRONTEND_PORT -eq 3000 ]; then
    print_error "Could not find an available port for frontend. Please free up a port in the range 3000-3010."
    exit 1
  fi
fi

# Check backend port
if is_port_in_use $BACKEND_PORT; then
  print_warning "Port $BACKEND_PORT is already in use. Finding an alternative port for backend..."
  # Try to find an available port
  for port in $(seq 8001 8010); do
    if ! is_port_in_use $port; then
      print_message "Using port $port for backend"
      BACKEND_PORT=$port
      break
    fi
  done
  
  if [ $BACKEND_PORT -eq 8000 ]; then
    print_error "Could not find an available port for backend. Please free up a port in the range 8000-8010."
    exit 1
  fi
fi

# Check database port
if is_port_in_use $DB_PORT; then
  print_warning "Port $DB_PORT is already in use. Finding an alternative port for database..."
  # Try to find an available port
  for port in $(seq 5433 5442); do
    if ! is_port_in_use $port; then
      print_message "Using port $port for database"
      DB_PORT=$port
      break
    fi
  done
  
  if [ $DB_PORT -eq 5432 ]; then
    print_error "Could not find an available port for database. Please free up a port in the range 5432-5442."
    exit 1
  fi
fi

# Create a .env file with the selected ports
print_message "Creating .env file with selected ports..."
cat > .env << EOF
# Generated by start-services.sh
FRONTEND_PORT=$FRONTEND_PORT
BACKEND_PORT=$BACKEND_PORT
DB_PORT=$DB_PORT

# Security (change these in production)
SECRET_KEY=your-secure-secret-key
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=30

# OpenAI
OPENAI_API_KEY=your-openai-api-key

# API configuration - for frontend to communicate with backend
API_URL=http://localhost:$BACKEND_PORT
EOF

print_message ".env file created or updated."

# Create a docker-compose.override.yml file
print_message "Creating docker-compose.override.yml with custom port mappings..."
cat > docker-compose.override.yml << EOF
version: '3.8'

services:
  backend:
    ports:
      - "127.0.0.1:$BACKEND_PORT:8000"
    environment:
      - PORT=8000

  frontend:
    ports:
      - "127.0.0.1:$FRONTEND_PORT:80"
    environment:
      - PORT=80

  db:
    ports:
      - "127.0.0.1:$DB_PORT:5432"
EOF

print_message "Override file created. Starting services with custom ports..."

# Start the services with the custom configuration
docker-compose up -d

print_message "Services started successfully!"
print_message "Frontend available at: http://localhost:$FRONTEND_PORT"
print_message "Backend API available at: http://localhost:$BACKEND_PORT/api"
print_message "Database available at: localhost:$DB_PORT" 