import { Box, Container, Typography, Link as MuiLink } from '@mui/material';
import { Link } from 'react-router-dom';

const EFFECTIVE_DATE = 'February 18, 2026';

const sections = [
  {
    title: '1. Acceptance of Terms',
    content: `By creating an account or using Acta AI, you agree to be bound by these Terms. If you do not agree, do not use the Service. We may update these Terms from time to time — continued use after changes constitutes acceptance.`,
  },
  {
    title: '2. Description of Service',
    content: `Acta AI is an AI-powered content generation and publishing platform. The Service allows you to connect third-party publishing platforms (such as WordPress), create content templates, schedule automated blog post generation using artificial intelligence, and publish content to your connected sites.`,
  },
  {
    title: '3. Account Registration',
    content: `You must provide accurate and complete information when creating an account. You are responsible for maintaining the confidentiality of your credentials and for all activity under your account. You must notify us immediately of any unauthorized use. You must be at least 18 years old to use the Service.`,
  },
  {
    title: '4. Acceptable Use',
    content: `You agree not to use the Service to:\n\n• Generate content that is unlawful, defamatory, harassing, threatening, or fraudulent\n• Produce spam, misleading content, or content intended to deceive search engines\n• Violate any applicable law, regulation, or third-party rights\n• Impersonate any person or entity\n• Attempt to gain unauthorized access to the Service or its systems\n• Resell, sublicense, or redistribute the Service without written permission\n\nWe reserve the right to suspend or terminate accounts that violate these terms.`,
  },
  {
    title: '5. AI-Generated Content',
    content: `Content produced by Acta AI is generated using third-party artificial intelligence models. You acknowledge that:\n\n• AI-generated content may contain inaccuracies, errors, or unintended outputs\n• You are solely responsible for reviewing, editing, and approving all content before publication\n• Acta AI does not guarantee that generated content is original, accurate, or free from bias\n• You assume full responsibility for any content published to your connected platforms\n• Generated content should be treated as a draft requiring human oversight`,
  },
  {
    title: '6. Third-Party Integrations',
    content: `The Service integrates with third-party platforms including WordPress, Shopify, and others. You are responsible for complying with the terms of service of any platform you connect. Acta AI is not responsible for the availability, performance, or policies of third-party services. Your API credentials for connected platforms are stored securely but are provided at your own risk.`,
  },
  {
    title: '7. Intellectual Property',
    content: `You retain ownership of any original content you provide to the Service (such as experience notes, custom instructions, and topic ideas). Content generated by the AI through the Service is provided to you for your use, subject to any applicable limitations of the underlying AI model providers. The Acta AI platform, including its design, code, and branding, remains the property of Acta AI.`,
  },
  {
    title: '8. Payment and Billing',
    content: `Certain features of the Service may require a paid subscription. By subscribing, you agree to pay the applicable fees. All fees are non-refundable except as required by law. We reserve the right to change pricing with reasonable notice. Failure to pay may result in suspension or termination of your account.`,
  },
  {
    title: '9. Data and Privacy',
    content: `Your use of the Service is also governed by our Privacy Policy, which describes how we collect, use, and protect your personal information. By using the Service, you consent to the practices described in the Privacy Policy.`,
  },
  {
    title: '10. Service Availability',
    content: `We strive to maintain reliable access to the Service but do not guarantee uninterrupted availability. The Service may be temporarily unavailable due to maintenance, updates, or circumstances beyond our control. We may also enter maintenance mode to temporarily pause AI generation capabilities.`,
  },
  {
    title: '11. Limitation of Liability',
    content: `To the maximum extent permitted by law, Acta AI shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service. This includes, without limitation, damages for loss of profits, data, business opportunities, or goodwill. Our total liability shall not exceed the amount you paid for the Service in the twelve (12) months preceding the claim.`,
  },
  {
    title: '12. Indemnification',
    content: `You agree to indemnify and hold harmless Acta AI, its officers, directors, employees, and agents from any claims, damages, losses, or expenses (including reasonable legal fees) arising from your use of the Service, your violation of these Terms, or any content you publish through the Service.`,
  },
  {
    title: '13. Termination',
    content: `You may delete your account at any time through your account settings. We may suspend or terminate your account if you violate these Terms or for any reason with reasonable notice. Upon termination, your data will be permanently deleted in accordance with our Privacy Policy. Content already published to third-party platforms will not be removed by us.`,
  },
  {
    title: '14. Governing Law',
    content: `These Terms shall be governed by and construed in accordance with applicable law. Any disputes arising from these Terms or your use of the Service shall be resolved through good-faith negotiation before pursuing formal legal action.`,
  },
  {
    title: '15. Contact',
    content: `If you have questions about these Terms, contact us at support@actaai.com.`,
  },
];

export default function TermsOfService() {
  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'background.default', py: 6 }}>
      <Container maxWidth="md">
        {/* Header */}
        <Box sx={{ mb: 5 }}>
          <Typography
            variant="h4"
            sx={{
              fontWeight: 900,
              textTransform: 'uppercase',
              letterSpacing: '0.04em',
              mb: 1,
              position: 'relative',
              display: 'inline-block',
              '&::after': {
                content: '""',
                position: 'absolute',
                bottom: -8,
                left: 0,
                width: '100%',
                height: 4,
                background: 'linear-gradient(90deg, #4A7C6F, #6B9E8A, transparent)',
              },
            }}
          >
            Terms of Service
          </Typography>
          <Typography variant="body2" sx={{ color: 'text.secondary', mt: 2 }}>
            Effective date: {EFFECTIVE_DATE}
          </Typography>
        </Box>

        {/* Intro */}
        <Typography variant="body1" sx={{ mb: 4, lineHeight: 1.8 }}>
          Welcome to Acta AI ("Service", "we", "us", or "our"). These Terms of Service govern your
          access to and use of the Acta AI platform. Please read them carefully.
        </Typography>

        {/* Sections */}
        {sections.map((section) => (
          <Box key={section.title} sx={{ mb: 4 }}>
            <Typography
              variant="h6"
              sx={{
                fontWeight: 700,
                textTransform: 'uppercase',
                letterSpacing: '0.03em',
                mb: 1.5,
                fontSize: '1rem',
              }}
            >
              {section.title}
            </Typography>
            <Typography
              variant="body1"
              sx={{ lineHeight: 1.8, whiteSpace: 'pre-line', color: 'text.secondary' }}
            >
              {section.content}
            </Typography>
          </Box>
        ))}

        {/* Footer links */}
        <Box
          sx={{
            mt: 6,
            pt: 3,
            borderTop: '1px solid',
            borderColor: 'divider',
            display: 'flex',
            gap: 3,
            flexWrap: 'wrap',
          }}
        >
          <MuiLink component={Link} to="/privacy" underline="hover" sx={{ fontWeight: 600 }}>
            Privacy Policy
          </MuiLink>
          <MuiLink component={Link} to="/" underline="hover" sx={{ fontWeight: 600 }}>
            Back to Acta AI
          </MuiLink>
        </Box>
      </Container>
    </Box>
  );
}
