"""Add variables to prompt templates

Revision ID: 12f0c86bbad8
Revises: 
Create Date: 2025-03-07 12:33:56.014683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12f0c86bbad8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_schedules', 'days_of_week')
    op.add_column('prompt_templates', sa.Column('variables', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    
    # Update existing records to have empty list for variables
    op.execute("UPDATE prompt_templates SET variables = '[]' WHERE variables IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_templates', 'variables')
    op.add_column('blog_schedules', sa.Column('days_of_week', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ### 