"""add_voice_seo_category_fields_to_templates

Revision ID: c92b12c3030f
Revises: ef4856d3bea2
Create Date: 2026-02-12 20:27:52.739706
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c92b12c3030f'
down_revision: Union[str, None] = 'ef4856d3bea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_templates', sa.Column('perspective', sa.String(length=20), nullable=True))
    op.add_column('prompt_templates', sa.Column('brand_voice_description', sa.Text(), nullable=True))
    op.add_column('prompt_templates', sa.Column('phrases_to_avoid', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('prompt_templates', sa.Column('personality_level', sa.Integer(), nullable=True))
    op.add_column('prompt_templates', sa.Column('use_anecdotes', sa.Boolean(), nullable=True))
    op.add_column('prompt_templates', sa.Column('use_rhetorical_questions', sa.Boolean(), nullable=True))
    op.add_column('prompt_templates', sa.Column('use_humor', sa.Boolean(), nullable=True))
    op.add_column('prompt_templates', sa.Column('use_contractions', sa.Boolean(), nullable=True))
    op.add_column('prompt_templates', sa.Column('seo_focus_keyword', sa.String(length=255), nullable=True))
    op.add_column('prompt_templates', sa.Column('seo_keywords', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('prompt_templates', sa.Column('seo_keyword_density', sa.String(length=20), nullable=True))
    op.add_column('prompt_templates', sa.Column('seo_meta_description_style', sa.String(length=50), nullable=True))
    op.add_column('prompt_templates', sa.Column('seo_internal_linking_instructions', sa.Text(), nullable=True))
    op.add_column('prompt_templates', sa.Column('default_categories', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('prompt_templates', sa.Column('default_tags', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_templates', 'default_tags')
    op.drop_column('prompt_templates', 'default_categories')
    op.drop_column('prompt_templates', 'seo_internal_linking_instructions')
    op.drop_column('prompt_templates', 'seo_meta_description_style')
    op.drop_column('prompt_templates', 'seo_keyword_density')
    op.drop_column('prompt_templates', 'seo_keywords')
    op.drop_column('prompt_templates', 'seo_focus_keyword')
    op.drop_column('prompt_templates', 'use_contractions')
    op.drop_column('prompt_templates', 'use_humor')
    op.drop_column('prompt_templates', 'use_rhetorical_questions')
    op.drop_column('prompt_templates', 'use_anecdotes')
    op.drop_column('prompt_templates', 'personality_level')
    op.drop_column('prompt_templates', 'phrases_to_avoid')
    op.drop_column('prompt_templates', 'brand_voice_description')
    op.drop_column('prompt_templates', 'perspective')
    # ### end Alembic commands ###
