"""add sites templates schedules posts tables

Revision ID: ef4856d3bea2
Revises: 11be94d96f08
Create Date: 2026-02-12 19:08:31.992523
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef4856d3bea2'
down_revision: Union[str, None] = '11be94d96f08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('topic_generation_prompt', sa.Text(), nullable=False),
    sa.Column('content_generation_prompt', sa.Text(), nullable=False),
    sa.Column('default_word_count', sa.Integer(), nullable=False),
    sa.Column('default_tone', sa.String(length=50), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('writing_style', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('audience_level', sa.String(length=50), nullable=True),
    sa.Column('special_requirements', sa.Text(), nullable=True),
    sa.Column('placeholders', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('variables', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wordpress_sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('api_url', sa.String(length=500), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('app_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('prompt_template_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('custom_cron', sa.String(length=100), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('time_of_day', sa.String(length=5), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('topics', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('tone', sa.String(length=50), nullable=True),
    sa.Column('include_images', sa.Boolean(), nullable=False),
    sa.Column('category_ids', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('tag_ids', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('prompt_replacements', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('post_status', sa.String(length=20), nullable=False),
    sa.Column('enable_review', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prompt_template_id'], ['prompt_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['wordpress_sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('wp_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['wordpress_sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('wp_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['wordpress_sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=True),
    sa.Column('prompt_template_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.String(length=500), nullable=True),
    sa.Column('featured_image_url', sa.String(length=1000), nullable=True),
    sa.Column('categories', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('wordpress_id', sa.Integer(), nullable=True),
    sa.Column('wordpress_url', sa.String(length=1000), nullable=True),
    sa.Column('system_prompt_used', sa.Text(), nullable=True),
    sa.Column('topic_prompt_used', sa.Text(), nullable=True),
    sa.Column('content_prompt_used', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['prompt_template_id'], ['prompt_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['blog_schedules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['wordpress_sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=True),
    sa.Column('execution_type', sa.String(length=20), nullable=False),
    sa.Column('execution_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['blog_posts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['blog_schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('execution_history')
    op.drop_table('blog_posts')
    op.drop_table('tags')
    op.drop_table('categories')
    op.drop_table('blog_schedules')
    op.drop_table('wordpress_sites')
    op.drop_table('prompt_templates')
    # ### end Alembic commands ###
